Add Breaking the Grip armbar game
trydydd/slimemoldgrappling pull request #37
Opened 2024-01-17 18:14 UTC by systay

Adds a new armbar game - "Breaking the Grip"

2024-01-17 18:14 UTC, systay commented
👋 making an experimental PR to see what you think about contributions

2024-01-17 18:50 UTC, trydydd commented
This is amazing! I'm overly excited about our first external contribution. 

I would only make two changes: 

- try to describe the starting position without using "spiderweb". This seems overly semantic, but we're working to keep things as understandable for complete novices as possible.
- Set the "weight" for _index.md in your file to 2 so that it sorts after maintaining the finish. All of the docs in this repo are sorted by weight in ascending order. 

Optional (but recommended):
- add an attribution section with your info (social media/github/website).

Once that's knocked out we'll get this merged and deployed.

Kudos to you for navigating this without any guidance for contributing -- the project is not well organized for collaboration (yet)!

2024-01-17 21:29 UTC, trydydd commented on content/games/submissions/arm_bar/breaking_the_grip/_index.md
> +weight = 1
Could we set this to 2 so that it sorts after the existing arm bar game in the nav menu?

2024-01-17 22:53 UTC, trydydd requested changes
It would be ideal to set the weight of the new _index.md to 2 so that it sorts below the existing game in the nav menu, and if you could explain the starting position without using "spiderweb" that would be really great. 

We're working to make it so that the content here is understandable for total novices with as little need to research things as possible.

2024-01-18 13:54 UTC, trydydd approved these changes

2024-01-18 13:55 UTC, merged